from node import Node, SinglyLinkedList

sll = SinglyLinkedList()
sll.sorted_insert(2)
print(sll.print_list())
sll.sorted_insert(5)
print(sll.print_list())
sll.sorted_insert(3)
sll.sorted_insert(10)
sll.sorted_insert(1)
sll.sorted_insert(-4)
sll.sorted_insert(-3)
sll.sorted_insert(4)
sll.sorted_insert(5)
sll.sorted_insert(12)
sll.sorted_insert(3)
# print(sll.print_list())
